# Assignment 1
- Name : Deepinder Singh Saini
- Roll No. : 102303673

**Question 1(a)**

In [20]:
import numpy as np

In [21]:
arr = np.array([1,2,3,4,5])
reverse = arr[::-1]
print("Reverse Array: ",reverse)

Reverse Array:  [5 4 3 2 1]


**Question 1(b)**

In [22]:
array1 = np.array([[1,2,3],
           [2,4,5],
           [1,2,3]])

flattened1 = array1.flatten()
print("Flattened Array using flatten returns copy: ",flattened1)

flattened2 = array1.ravel()
print("Flattened Array using ravel returns original: ",flattened2)



Flattened Array using flatten returns copy:  [1 2 3 2 4 5 1 2 3]
Flattened Array using ravel returns original:  [1 2 3 2 4 5 1 2 3]


**Question 1(c)**

In [23]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[1,2],[3,4]])

np.array_equal(arr1,arr2)

True

**Question 1(d)**

In [24]:
#1
x = np.array([1,2,3,4,5,1,2,1,1,1])
values,counts = np.unique(x,return_counts=True)
most_freq_val = values[np.argmax(counts)]

indices = np.where(x == most_freq_val)[0]

print("Most frequent value in x:",most_freq_val)
print("Indices: ",indices)

Most frequent value in x: 1
Indices:  [0 5 7 8 9]


In [25]:
#2
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
values1,counts1 = np.unique(y,return_counts=True)
most_freq_val1 = values1[np.argmax(counts1)]

indices1 = np.where(y == most_freq_val1)[0]

print("Most frequent value in y:",most_freq_val1)
print("Indices: ",indices1)

Most frequent value in y: 1
Indices:  [0 1 2]


**Question 1(e)**

In [26]:
gfg = np.matrix('[4,1,9;12,3,1;4,5,6]')
sum_gfg = gfg.sum()
sum_row_gfg = gfg.sum(axis=1)
sum_col_gfg = gfg.sum(axis=0)
print("Sum= ",sum_gfg)
print("Row Sum= ",sum_row_gfg)
print("Column Sum= ",sum_col_gfg)

Sum=  45
Row Sum=  [[14]
 [16]
 [15]]
Column Sum=  [[20  9 16]]


**Question 1(f)**

In [27]:
n_array = np.array([[55,25,15],
                    [30,44,2],
                    [11,45,77]])

#1
sum_diagonal = np.trace(n_array)
print("Sum of Diagonals: ",sum_diagonal)

#2
eigenvalues , eigenvector = np.linalg.eig(n_array)
print("Eigen Values: ",eigenvalues)

#3
print("Eigen Vector: ",eigenvector)

#4
inverse = np.linalg.inv(n_array)
print("Inverse: ",inverse)

#5
determinant = np.linalg.det(n_array)
print("Determinant: ",determinant)

Sum of Diagonals:  176
Eigen Values:  [98.16835147 28.097044   49.73460452]
Eigen Vector:  [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse:  [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant:  137180.0000000001


**Question 1(g)**

In [28]:
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])

product1 = np.dot(p1,q1)
print("Multiplication 1: ",product1)
cov1 = np.cov(p1.flatten(),q1.flatten())
print("Covariance 2: ",cov1)

p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])

product2 = np.dot(p2, q2)
print("Multiplication 1: ",product2)
cov2 = np.cov(p2.flatten(),q2.flatten())
print("Covariance 2: ",cov2)

Multiplication 1:  [[16 19]
 [26 31]]
Covariance 2:  [[0.66666667 1.        ]
 [1.         1.66666667]]
Multiplication 1:  [[16 19  5]
 [26 31  8]
 [46 55 14]]
Covariance 2:  [[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


**Question 1(h)**

In [29]:
x = np.array([[2, 3, 4],
              [3, 2, 9]])

y = np.array([[1, 5, 0],
              [5, 10, 3]])

#1
inner = np.inner(x,y)
print("Inner Product: ",inner)

#2
outer = np.outer(x.flatten(),y.flatten())
print("Outer Product: ",outer)


Inner Product:  [[17 52]
 [13 62]]
Outer Product:  [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]


**Question 2(a)**


In [30]:
array = np.array([[1, -2, 3],
                  [-4, 5, -6]])

#1
abs_value = np.abs(array)
print("Absolute Value: ",abs_value)

#2
percentile_flattened = np.percentile(array.flatten(),[25,50,75])
print("FLattend Array Percentile: ",percentile_flattened)

percentile_row = np.percentile(array,[25,50,75],axis=1)
print("Row Percentile: ",percentile_row)

percentile_col = np.percentile(array,[25,50,75],axis=0)
print("Column Percentile: ",percentile_col)

#3
mean_flatten = np.mean(array.flatten())
median_flatten = np.median(array.flatten())
sd_flatten = np.std(array.flatten())
print("Mean Flatten: ",mean_flatten)
print("Median Flatten: ",median_flatten)
print("SD Flatten: ",sd_flatten)

mean_row = np.mean(array,axis=1)
median_row = np.median(array,axis=1)
sd_row = np.std(array,axis=1)
print("Mean Row: ",mean_row)
print("Median Row: ",median_row)
print("SD Row: ",sd_row)

mean_col = np.mean(array,axis=0)
median_col = np.median(array,axis=0)
sd_col = np.std(array,axis=0)
print("Mean col: ",mean_col)
print("Median col: ",median_col)
print("SD col: ",sd_col)

Absolute Value:  [[1 2 3]
 [4 5 6]]
FLattend Array Percentile:  [-3.5 -0.5  2.5]
Row Percentile:  [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
Column Percentile:  [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Mean Flatten:  -0.5
Median Flatten:  -0.5
SD Flatten:  3.8622100754188224
Mean Row:  [ 0.66666667 -1.66666667]
Median Row:  [ 1. -4.]
SD Row:  [2.05480467 4.78423336]
Mean col:  [-1.5  1.5 -1.5]
Median col:  [-1.5  1.5 -1.5]
SD col:  [2.5 3.5 4.5]


**Question 2(b)**

In [31]:
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])

floor_a = np.floor(a)
ceil_a = np.ceil(a)
trunc_a = np.trunc(a)
round_a = np.round(a)

print("Floor: ",floor_a)
print("Ceil: ",ceil_a)
print("Truncated Values: ",trunc_a)
print("Rounded values: ",round_a)

Floor:  [-2. -2. -1.  0.  1.  1.  3.]
Ceil:  [-1. -1. -0.  1.  2.  2.  3.]
Truncated Values:  [-1. -1. -0.  0.  1.  1.  3.]
Rounded values:  [-2. -2. -0.  0.  2.  2.  3.]


**Question 3(a)**

In [32]:
array = np.array([10, 52, 62, 16, 16, 54, 453])

#1
sorted_array = np.sort(array)

#2
sorted_indices = np.argsort(array)

#3
smallest = np.sort(array)[:4]

#4
largest = np.sort(array)[-5:]

print("Sorted array:", sorted_array)
print("Indices of sorted array:", sorted_indices)
print("4 smallest elements:", smallest)
print("5 largest elements:", largest)



Sorted array: [ 10  16  16  52  54  62 453]
Indices of sorted array: [0 3 4 1 5 2 6]
4 smallest elements: [10 16 16 52]
5 largest elements: [ 16  52  54  62 453]


**Question 3(b)**

In [33]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
integer_elements = array[np.floor(array) == array]
float_elements = array[np.floor(array) != array]

print("Integers Only: ",integer_elements)
print("Float Only: ",float_elements)

Integers Only:  [1. 2. 3. 2.]
Float Only:  [1.2 2.2]
